ALTER TABLE item ADD COLUMN IF NOT EXISTS shop_id BIGINT;

ALTER TABLE item ADD COLUMN IF NOT EXISTS item_order INT;

ALTER TABLE item DROP CONSTRAINT IF EXISTS fk_item_shop;
ALTER TABLE item ADD CONSTRAINT fk_item_shop
FOREIGN KEY (shop_id) REFERENCES shop(id);